[workspace]
authors = ["d-laub <dlaub@ucsd.edu>"]
channels = ["conda-forge"]
name = "genoray-cli"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
publish = "rm -rf dist && uv publish"

[dependencies]
python = ">=3.9,<3.13"
cyclopts = "*"

[pypi-dependencies]
genoray-cli = { path = ".", editable = true }
genoray = "*"
